### DISCUSSION TITLE
[SOLVED] Experience with deployment on a larger NPM reverse proxy (RAM, standalone, etc.)

### DISCUSSION THREAD

**Discussion by antoninchadima** [openappsec/openappsec#249] [General]
Hi, 

It is a shame that open-appsec doesn't have a designated community or user forum. Maybe there is no need for it, and it would be unused.

I have migrated from an existing Nginx Proxy Manager deployment and followed the documentation on:
[https://docs.openappsec.io/troubleshooting/troubleshooting-guides/how-to-migrate-from-an-existing-nginx-proxy-manager-deployment-and-keep-configuration](https://docs.openappsec.io/troubleshooting/troubleshooting-guides/how-to-migrate-from-an-existing-nginx-proxy-manager-deployment-and-keep-configuration)
The document should mention that after switching to and loading the new NPM pages, the browser's cache and cookies must be cleared.

I have migrated a reverse proxy serving more than 100 different websites. After 12 hours, the server ran out of memory (everything stopped working), and I had to upgrade the RAM to 128GB. This fact should be mentioned somewhere in the requirements. But maybe it is a (memory leak?) bug. Because the used memory is still rising. It seems that even 256GB would not be enough.

Thanks to the documentation 
[https://docs.openappsec.io/integrations/nginx-proxy-manager-integration/install-nginx-proxy-manager-with-open-appsec-managed-from-npm-webui](https://docs.openappsec.io/integrations/nginx-proxy-manager-integration/install-nginx-proxy-manager-with-open-appsec-managed-from-npm-webui)
I have managed to deploy the open-appsec WAF successfully in a standalone mode. I have used the (beta) docker compose.
[https://raw.githubusercontent.com/openappsec/openappsec/refs/heads/main/deployment/docker-compose/nginx-proxy-manager/docker-compose.yaml](https://raw.githubusercontent.com/openappsec/openappsec/refs/heads/main/deployment/docker-compose/nginx-proxy-manager/docker-compose.yaml)
But saving the open-appsec options in NPM didn't work.  

```
Error notifying openappsec to apply the policy on port 7777: Command failed: curl -s -o /dev/null -w "%{http_code}" --data '{"policy_path":"/etc/cp/conf/local_policy.yaml"}' http://127.0.0.1:7777/set-apply-policy
Error notifying openappsec to apply the policy on port 7778: Command failed: curl -s -o /dev/null -w "%{http_code}" --data '{"policy_path":"/etc/cp/conf/local_policy.yaml"}' http://127.0.0.1:7778/set-apply-policy
```

I had to change the appsec-agent service to use the network mode service:nginx or open the 7777 port in the appsec-agent service configuration. After that it works.

```
Policy applied successfully on port 7777
```

This is my simple version of docker-compose.yaml file with the change (I'm not sure about the usefulness of the ipc directives):

```
services:
  appsec-agent:
    image: ghcr.io/openappsec/agent
    command: /cp-nano-agent
    volumes:
    - advanced-model:/advanced-model
    - appsec-config:/etc/cp/conf
    - appsec-data:/etc/cp/data
    - appsec-localconfig:/ext/appsec
    - appsec-logs:/var/log/nano_agent
    network_mode: service:nginx
    environment:
    - AGENT_TOKEN=cp-xxx
    - LEARNING_HOST=appsec-smartsync
    - SHARED_STORAGE_HOST=appsec-shared-storage
    - TUNING_HOST=appsec-tuning-svc
    - autoPolicyLoad=true
    - nginxproxymanager=true
    - user_email=xxx
    ipc: host
    restart: unless-stopped
  appsec-db:
    image: postgres
    volumes:
    - appsec-postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=xxx
    - POSTGRES_USER=postgres
    restart: unless-stopped
  appsec-shared-storage:
    image: ghcr.io/openappsec/smartsync-shared-files
    volumes:
    - appsec-smartsync-storage:/db:z
    ipc: host
    restart: unless-stopped
  appsec-smartsync:
    image: ghcr.io/openappsec/smartsync
    environment:
    - SHARED_STORAGE_HOST=appsec-shared-storage
    depends_on:
    - appsec-shared-storage
    restart: unless-stopped
  appsec-tuning-svc:
    image: ghcr.io/openappsec/smartsync-tuning
    volumes:
    - appsec-config:/etc/cp/conf
    environment:
    - QUERY_DB_HOST=appsec-db
    - QUERY_DB_PASSWORD=xxx
    - QUERY_DB_USER=postgres
    - SHARED_STORAGE_HOST=appsec-shared-storage
    depends_on:
    - appsec-db
    - appsec-shared-storage
    restart: unless-stopped
  nginx:
    image: ghcr.io/openappsec/nginx-proxy-manager-attachment
    volumes:
    - appsec-localconfig:/ext/appsec
    - appsec-logs:/ext/appsec-logs
    - data:/data
    - letsencrypt:/etc/letsencrypt
    ports:
    - 443:443
    - 81:81
    - 80:80
    ipc: host
    restart: unless-stopped
volumes:
  advanced-model:
  appsec-config:
  appsec-data:
  appsec-localconfig:
  appsec-logs:
  appsec-postgres-data:
  appsec-smartsync-storage:
  data:
  letsencrypt:
  sites:
```

Still after that it seems that the local-policy.yaml file gets updated and the appsec-agent service is informed on port 7777, but the local policy isn't applied. I have to manually run `open-appsec-ctl --apply-policy` . Before running this command to apply policy the open-appsec tuning tool seas only one asset "Any". After running this command there are at the "View statistics" more than hundred :stuck_out_tongue_winking_eye: assets listed (configured in the NPM Web UI). The list is so long that it makes this tool unusable... Updating policy is needed after every docker open-appsec agent service restart. 

Afterwards I have struggled with the lack of the standalone mode configuration via local-policy.yaml. I found only 
[https://docs.openappsec.io/getting-started/start-with-linux/local-policy-file-advanced](https://docs.openappsec.io/getting-started/start-with-linux/local-policy-file-advanced) and [https://docs.openappsec.io/getting-started/start-with-docker/configuration-using-local-policy-file-docker](https://docs.openappsec.io/getting-started/start-with-docker/configuration-using-local-policy-file-docker)
But it got me more confused: for example some documentation mentions `/ext/appsec` as a directory, other places treats it as a file `vi /ext/appsec` etc.

So I decided to connect the agent to the open-appsec SaaS Web UI using a provided token in the docker compose environments parametres. This worked out, but I didn't find any documented way to go back and disconnect the agent from the SaaS Web UI and reconfigure it to be in a standalone mode again... I had to completely wipe out the configuration to achieve this goal (I hope there is a better way).

I have decided to try out the declarative policy using the open-appsec local configuration file. But this option is for Nginx Proxy Manager  inactive. Therefore I have created a profile for Linux Embedded Agent NGINX application security. What could possibly go wrong if the communication is only one way: open-appsec agent -> open-appsec SaaS Web UI? This is kind of working with some caveats. 
- All the created assets didn't get loaded for viewing, only the default backend.
- Every time after restarting the open-appsec agent docker service there is a new agent in the SaaS UI with a different UID and Host, These values are not persistent across restarts.
- The monitoring dashboard shows Overall HTTP Traffic 0 Sources, Malicious Activity 0 Assets Targeted and 0 Suspected Sources,
Security Actions 0 Prevents and 0 Detects
- The monitoring dashboard shows No results found at Top Attack Sources High And Above, Attacks Timeline, Attacks Level and Top Attacked Assets. Only the Assets Statistics table is OK.
- The statistics are different then from `open-appsec-tuning-tool`
-  The monitoring ALL EVENTS tab doesn't show any useful information only the Asset Name of the local policy (No Security Action, Source IP etc.)
- In the monitoring IMPORTANT EVENTS tab I get lot of critical events: Agent could not update policy to version (Not sure what does this mean)

**I have tried out a lot of things and spend a lot of time using a trial and error method. The whole process of configuring a standalone version of open-apsec WAF seems to have a lot of rough edges.** Hoping to understand more this wonderful piece of software. I'm not sure and thinking about going back to pure Nginx Proxy Manger.

My open-appsec agent status `open-appsec-ctl --status`:
```
---- open-appsec Nano Agent ----
Version: 1.1.21-open-source
Status: Running
AI model version: Advanced model V2.0
Management mode: Cloud management (Visibility mode)
Agent ID: xxx
Profile ID: xxx
Policy files: 
    /ext/appsec/local_policy.yaml
Policy load status: Success
Last policy update: 2025-02-04T10:13:02.472354

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.21-open-source, Created at: 2025-01-21T08:08:18+0000
Status: Running

---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.21-open-source, Created at: 2025-01-21T08:08:18+0000
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.21-open-source, Created at: 2025-01-21T08:08:18+0000
Registered Instances: 32
Status: Running

For release notes and known limitations check: https://docs.openappsec.io/release-notes
For troubleshooting and support: https://openappsec.io/support
```

PS: on a 12.x" Full HD screen is no need to display in the SaaS UI: "Display resolution below recommended (minimum 13"), Consider upgrading for optimal experience."
PPS: going through all the files in a standalone deployment I'm confused for example with the `redis.conf` file etc. There a lot of configuration files deployed, a lot of source code on Github and I'm still not getting it all...
