### ISSUE TITLE
Questions related to configurations via CRDs.

### ISSUE THREAD

**Issue by 5hin0bi** [openappsec/openappsec#105]
Hello!

I got multiple questions if you let me, please. Using version 1.1.5 here. (Not connected to the WebUI console). Latest image.

1. Do countryCode based exceptions work if using k8s with CRDs? I've seen the issue resolved, not in my case unfortunatelly.

2. What is the order of the exceptions? E.g. I got a policy that works for all the ingresses defined in my cluster. Since the limitation I define countryCode based rules in separate exception CRD.
```
---
apiVersion: openappsec.io/v1beta1
kind: Policy
metadata:
    name: open-webapp-best-practice-policy
spec:
    default:
        mode: prevent
        practices:
            - webapp-best-practice
        triggers:
            - appsec-special-log-trigger
        custom-response: 403-forbidden
        exceptions:
            - appsec-exception-country-code # drop ES (Spain)
            - appsec-exception-general # accept "wp-(.*)"
```
What happens to one requesting https://example.com/wp-admin from Spain? Would he be dropped or accepted?
Didn't find the explanation for the CRD case on the website, sorry.

3. Today we faced DDoS attack and couldn't do anything with it since country based rules didn't work and there are no CRDs to define DDoS mitigations rules too. :<
I cannot use WebUI since the company security policies.
