### ISSUE TITLE
OpenAppsec Best policy rule blocking requests even in detect-learn mode

### ISSUE THREAD

**Issue by ksgnextuple** [openappsec/openappsec#139]
Hi

This is my current configuration:

Kong: 3.6
KIC: 
AppSec: 1.1.8

Configured yaml for the security Policy:

```
apiVersion: openappsec.io/v1beta1
kind: Policy
metadata:
  annotations:
  generation: 1
  name: open-appsec-best-practice-policy
spec:
  default:
    custom-response: 403-forbidden
    exceptions: []
    mode: detect-learn
    practices:
    - appsec-best-practice
    source-identifiers: ""
    triggers:
    - appsec-log-trigger
    trusted-sources: ""
```

Even though it is detect-learn mode few requests are getting blocked. Any resoultion for this?
