### ISSUE TITLE
Warning: cannot overwrite table with non table for open-appsec-k8s-nginx-ingress.appsec.persistence.learning.storageClass (map[accessModes:ReadWriteMany name:<nil>])

### ISSUE THREAD

**Issue by gwsampso** [openappsec/openappsec#142]
Hello

When running the following code 

```
helm install .\open-appsec-k8s-nginx-ingress-latest.tgz \ 
--name-template=open-appsec \
--set appsec.mode=managed \
--set appsec.agentToken=cp-81e1fc5c...... \
--set controller.ingressClass=appsec-nginx \
--set controller.ingressClassResource.name=appsec-nginx \
--set controller.ingressClassResource.controllerValue="k8s.io/appsec-nginx" \
--set appsec.persistence.enabled=true \
--set appsec.persistence.learning.storageClass=open-appsec-learning \
 --set controller.service.externalTrafficPolicy=Local \
--set appsec.userEmail=email.com \
-n appsec --create-namespace
```

I encounter the warning Warning: cannot overwrite table with non table for open-appsec-k8s-nginx-ingress.appsec.persistence.learning.storageClass (map[accessModes:ReadWriteMany name:<nil>])

This is my storage YAML 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
     name: open-appsec-learning
provisioner: file.csi.azure.com
parameters:
  shareName: open-appsec-learning
  storageAccount: accountname
  resourceGroup: resourcegroup
reclaimPolicy: Delete

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: open-appsec-data
  annotations:
    volume.beta.kubernetes.io/storage-class: open-appsec-learning
spec:
  storageClassName: open-appsec-learning
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
```
      
additionally if i run helm upgrade i encounter the warning as well
```
helm upgrade open-appsec open-appsec-k8s-nginx-ingress-latest.tgz -n appsec --reuse-values --set appsec.mode=managed --set appsec.agentToken=cp-8060ff53-....
```

**Comment by jeffreyflynt** [comment]
To get this working, I had to use: 

```
appsec:
  persistence:
    enabled: true
    learning:
      storageClass:
        name: nameHere
```
