### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by jeffreyflynt** [openappsec/openappsec#147]
In Kubernetes, for the `open-appsec` container, I'm getting this in the logs:

```
Starting installation of open-appsec Nano Agent [Sat Jun 15 22:46:42 UTC 2024]
Creating env details file
Copying cp-nano-agent binary file to folder: /etc/cp/orchestration/cp-nano-orchestration
Run Orchestration nano service in hybrid mode
Installing the watchdog
Start cp-nano-agent service
Note: in order for the agent to remain active and effective it must connect to the Fog/Cloud at least every 45 days
open-appsec Orchestration Nano Service installation completed successfully
cat: /etc/cp/orchestration/hybrid-check-update.pid: No such file or directory
cat: /etc/cp/conf/agent_details.json: No such file or directory
cat: /etc/cp/conf/agent_details.json: No such file or directory
...
```

The line: `cat: /etc/cp/conf/agent_details.json`: No such file or directory` just continually logs and none of the exceptions or policies work. This is on a new install in standalone mode.

Here is the relevant Helm Chart:

```
appsec:
  persistence:
    enabled: true
    learning:
      storageClass:
        name: encrypted-rwo
        accessModes: ReadWriteOnce
      size: 50Gi
  mode: standalone
  ```
  
  Any ideas?
