### ISSUE TITLE
Persisting Agents in Portal > Agents via Docker

### ISSUE THREAD

**Issue by jiriteach** [openappsec/openappsec#159]
Hi - I have noticed that when the agent (which is deployed via Docker) is restarted - a new Agent is created in the Portal. Is this expected or how can I persist the same agent.

Thanks

**Comment by jiriteach** [comment]
Just restarting the Docker container for the agent - so using docker-compose up -d or Portainer for a restart of the container. Everytime it does - the agent ID changes.  Any options to persist this? And in the portal - you end up with stale agents.

**Comment by orianelou** [comment]
Hi @jiriteach, 

We'll look into it, can you please confirm that you're using volume mounts for agent data and config?

**Comment by jiriteach** [comment]
Thanks and yes I am using volume mounts as below - 

```
version: '3.3'
services:
  appsec-npm:
    container_name: appsec-npm
    image: 'ghcr.io/openappsec/nginx-proxy-manager-centrally-managed-attachment:latest'
    ipc: host
    restart: unless-stopped
    ports:
      - '443:443'
      - '81:81'
    volumes:
      - /home/administrator/Docker/appsec/data:/data
      - /home/administrator/Docker/appsec/letsencrypt:/etc/letsencrypt

  appsec-agent:
    container_name: appsec-node
    image: 'ghcr.io/openappsec/agent:latest'
    ipc: host
    restart: unless-stopped
    environment:
      - user_email=xxx@xxx.xxx.xxx
      - nginxproxymanager=true
    volumes:
      - /home/administrator/Docker/appsec/appsec-config:/etc/cp/conf
      - /home/administrator/Docker/appsec/appsec-data:/etc/cp/data
      - /home/administrator/Docker/appsec/appsec-logs:/var/log/nano_agent
      - /home/administrator/Docker/appsec/appsec-advanced-model/open-appsec-advanced-model.tgz:/advanced-model/open-appsec-advanced-model.tgz:rw
    command: /cp-nano-agent --token xxx
```
