### ISSUE TITLE
NGINX reverse proxy (including open-appsec attachment) - restart NGINX

### ISSUE THREAD

**Issue by cm91** [openappsec/openappsec#161]
Hi,

i did some more testing with the new unified container (openappsec agent + nginx attachment combined).
It turned out, that a container restart ("docker restart container" or "docker stop container && docker start container")
doesn't reload or restart the nginx server.
This would be helpful in case of config changes or if a new certificate should be loaded. Currently i have to do a re-deployment to publish changes or reload a certificate.

Is this expected or is this something that can possibly be fixed with one of the next releaeses?

Thanks,
Christian

**Comment by orianelou** [comment]
Hi @cm91, 

Thank you for the feedback, the NGINX should restart. Will it be possible for you to share the docker run or compose you've used so we can recreate the issue?

Best, 

The open-appsec team

**Comment by cm91** [comment]
Hi, thanks for the feedback. Sure, this is my docker-compose file which was then used with the "docker-compose up -d" command:

```
version: "3"
services:
  waf-test:
    image: ghcr.io/openappsec/agent-unified:latest
    restart: unless-stopped
    container_name: waf-test
    hostname: 'waf-test'
    ipc: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/certs:/opt/certs
      - ${PWD}/waf_app/conf:/etc/cp/conf
      - ${PWD}/waf_app/data:/etc/cp/data
      - ${PWD}/waf_app/logs:/var/log/nano_agent
      - ${PWD}/waf_app/alm/open-appsec-advanced-model.tgz:/advanced-model/open-appsec-advanced-model.tgz
      - ${PWD}/waf_app/nginx:/etc/nginx/conf.d

    ports:
      - 80:80
      - 443:443

    environment:
      - user_email=my-email
      - AGENT_TOKEN=token

    command: /cp-nano-agent --token token
```


After bringing it up, it works as expected. Example in my case (i did a curl to the internal docker container IP address. I do redirect all requests on port 80):

curl -v 192.168.128.2
*   Trying 192.168.128.2:80...
* Connected to 192.168.128.2 (192.168.128.2) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.128.2
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Tue, 23 Jul 2024 07:58:28 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://192.168.128.2/
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>


Then do a docker restart waf-test and re-test the curl command:

curl -v 192.168.128.2
*   Trying 192.168.128.2:80...
* Connected to 192.168.128.2 (192.168.128.2) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.128.2
> User-Agent: curl/7.88.1
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

In the container i also did a "ps" and there is no nginx process.


The nginx did not (re)start. To fix this, i have to jump into the container and start nginx manually with the "nginx" command.

Thanks,
Christian
