### ISSUE TITLE
appsec-agent time offset

### ISSUE THREAD

**Issue by gonsaaa** [openappsec/openappsec#180]
Hello,

I'm using Nginx Proxy Manager with app-sec with docker container.
Although I set the enviroment in the docker compose to my correct timezone, it doesn't work.

```
services:
  appsec-npm:
    container_name: npm-attachment
    image: 'ghcr.io/openappsec/nginx-proxy-manager-attachment:latest'
    ipc: host
    restart: unless-stopped
    ports:
      - '4080:80' # Public HTTP Port
      - '40443:443' # Public HTTPS Port
      - '4081:81' # Admin Web Port
    volumes:
      - /nfs/share/data/npm_original/data:/data
      - /nfs/share/data/npm_original/letsencrypt:/etc/letsencrypt
      - /nfs/share/data/npm_original/data/force-ssl.conf:/etc/nginx/conf.d/include/force-ssl.conf
      - /nfs/share/data/npm_original/config.json:/app/config/production.json
      - /nfs/share/data/appsec/logs:/ext/appsec-logs
      - /nfs/share/data/appsec/localconfig:/ext/appsec
    environment:
      - TZ=Europe/Lisbon

  appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    network_mode: service:appsec-npm
    ipc: host
    restart: unless-stopped
    environment:
      # adjust with your own email below
      - user_email=email@email
      - nginxproxymanager=true
      - autoPolicyLoad=true
      - TZ=Europe/Lisbon
    volumes:
      - /nfs/share/data/appsec/config:/etc/cp/conf
      - /nfs/share/data/appsec/data:/etc/cp/data
      - /nfs/share/data/appsec/logs:/var/log/nano_agent
      - /nfs/share/data/appsec/localconfig:/ext/appsec
    command: /cp-nano-agent --standalone
```

It works in the npm container but not in the appsec-agent.
Logging in to the appsec-agent container and checking the date shows a different hour as well as in the security logs.

![2024-08-30 09_44_31-Portainer _ vmdocker — Mozilla Firefox](https://github.com/user-attachments/assets/98883f8f-87f0-4822-a3c2-b337046a6410)
![2024-08-30 09_44_09-Portainer _ vmdocker — Mozilla Firefox](https://github.com/user-attachments/assets/32d95a6b-6df0-43f5-8dfd-c7aedb28f341)
