### ISSUE TITLE
syslog-service not working in local_policy

### ISSUE THREAD

**Issue by mik0s** [openappsec/openappsec#187]
I'm trying to send logs to syslog server using local management. 
I added the syslog-service key to the default config local_policy.yaml, applied the policy, but the setting did not appear in policy.yaml.

local_policy.yaml
```
log-triggers:
  - name: appsec-default-log-trigger
    access-control-logging:
      allow-events: false
      drop-events: true
    additional-suspicious-events-logging:
      enabled: true
      minimum-severity: high
      response-body: false
    appsec-logging:
      all-web-requests: false
      detect-events: true
      prevent-events: true
    extended-logging:
      http-headers: false
      request-body: false
      url-path: false
      url-query: false
    log-destination:
      cloud: false
      syslog-service:
      - address: 192.168.1.10
        port: 514
```

policy.yaml
```
{
    "accessControlV2": {
        "rulebase": {
            "accessControl": [],
            "traditionalFirewall": [],
            "l4firewall": [],
            "rateLimit": []
        }
    },
    "waap": {
        "WAAP": {
            "WebAPISecurity": [],
            "WebApplicationSecurity": [
                {
...
                    "triggers": [
                        {
                            "$triggerType": "log",
                            "id": "1265e5ab-d09b-4af0-85e7-89b294bd5539",
                            "name": "local_policy/appsec-default-log-trigger",
                            "log": {
                                "context": "triggerId(1265e5ab-d09b-4af0-85e7-89b294bd5539)",
                                "triggerName": "local_policy/appsec-default-log-trigger",
                                "triggerType": "log",
                                "verbosity": "Standard",
                                "acAllow": false,
                                "acDrop": true,
                                "complianceViolations": false,
                                "complianceWarnings": false,
                                "extendLoggingMinSeverity": "high",
                                "extendLogging": true,
                                "logToAgent": true,
                                "logToCef": false,
                                "logToCloud": false,
                                "logToK8sService": false,
                                "logToSyslog": false,
                                "responseBody": false,
                                "responseCode": false,
                                "tpDetect": true,
                                "tpPrevent": true,
                                "webBody": false,
                                "webHeaders": false,
                                "webRequests": false,
                                "webUrlPath": false,
                                "webUrlQuery": false,
                                "urlForSyslog": ":514",
                                "urlForCef": ":0",
                                "formatLoggingOutput": false
                            }
                        }

```

Accordingly, nothing is sent to syslog. How do I enable syslog in local_policy.yaml?

**Comment by orianelou** [comment]
Hi @mik0s, 

We had an issue in our docs, the address shouldn't be part of an array, we've adjusted them thank you for the feedback! Please adjust the log trigger and reapply policy. 

```
log-triggers:
  - name: appsec-default-log-trigger
    access-control-logging:
      allow-events: false
      drop-events: true
    additional-suspicious-events-logging:
      enabled: true
      minimum-severity: high
      response-body: false
    appsec-logging:
      all-web-requests: false
      detect-events: true
      prevent-events: true
    extended-logging:
      http-headers: false
      request-body: false
      url-path: false
      url-query: false
    log-destination:
      cloud: false
      syslog-service:
       address: 192.168.1.10
        port: 514
```
