### ISSUE TITLE
Configure https protocol instead of http

### ISSUE THREAD

**Issue by pablo-garcia-clikalia** [openappsec/openappsec#192]
Hi,

I've configured Open AppSec in Kubernetes following [documentation](https://docs.openappsec.io/getting-started/start-with-kubernetes/install-using-helm-ingress-nginx-and-kong). When creates the asset in Management Portal it set protocol to http instead of https and I cannot modify it because its not managed.

values.yaml
```yaml
open-appsec-k8s-nginx-ingress:
  appsec:
    mode: managed
    agentToken: agentToken
    persistence:
      enabled: false
  controller:
    ingressClass: appsec-nginx
    allowSnippetAnnotations: true
    extraArgs:
      enable-ssl-passthrough: true
    ingressClassResource:
      name: appsec-nginx
      controllerValue: k8s.io/appsec-nginx
    service:
      type: ClusterIP
      annotations:
        cloud.google.com/neg: '{"exposed_ports": {"443":{"name": "ingress-appsec-nginx-443-neg"}}}'
```

ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 128M
    nginx.ingress.kubernetes.io/proxy-buffer-size: 24k
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    openappsec.io/policy: open-appsec-best-practice-policy
spec:
  tls:
    - hosts:
        - web.domain.com
  ingressClassName: appsec-nginx
  rules:
    - host: web.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
```

What do I have to add/change to configure it as https?

Thanks a lot!
