### ISSUE TITLE
It is not possible to set nodeSelector and tolerations if `appsec.persistence.enabled` set to false

### ISSUE THREAD

**Issue by anatolek** [openappsec/openappsec#219]
The last open-appsec-k8s-nginx-ingress helm chart (4.11.3) has a bug where It is not possible to set nodeSelector and tolerations if `appsec.persistence.enabled` is set to false.

This is a part of the `learning-deployment.yaml` template

```yaml
...
          env:
            - name: SHARED_STORAGE_HOST
              value: {{ .Release.Name }}-{{ .Values.appsec.storage.name }}-svc
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- if eq .Values.appsec.persistence.enabled true }}
          volumeMounts:
            - mountPath: /tmp/locks/
              name: flock
	{{- if .Values.appsec.learning.nodeSelector }}
      nodeSelector: {{ toYaml .Values.appsec.learning.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.appsec.learning.tolerations }}
      tolerations: {{ toYaml .Values.appsec.learning.tolerations | nindent 8 }}
    {{- end }}
      volumes:
        - name: flock
          persistentVolumeClaim:
            claimName: {{ .Values.appsec.name }}-storage
      {{- end }}
...
```

I would be happy to fix this issue and make a pull request, but it seems the current chart in this repo is already outdated and not relevant.
