### ISSUE TITLE
Where to set Truted source IP in local_policy.,yml

### ISSUE THREAD

**Issue by piotr-sikora-v** [openappsec/openappsec#246]
Sorry but I can't understand where I can set IP addresses as Trusted Source.

as far I set:
```
policies:
  default:
....
  specific-rules:
  - host: "beta.xxxx.com"
    triggers:
    - appsec-log-trigger
    mode: detect-learn
    practices:
    - appsec-best-practice
    custom-response: appsec-default-web-user-response
    trustedsources:
    - name: appsec-trusted-source-good-ppl
      minNumOfSources: 1
      sourcesIdentifiers: [appsec-source-identifiers-sourceip]
```
and at end:
```
source-identifiers:
  - name: appsec-source-identifiers-sourceip
    identifiers:
    - sourceIdentifier: sourceip
```
but on https://docs.openappsec.io/getting-started/start-with-linux/local-policy-file-advanced I didn't found where I can put list of IP's
