### ISSUE TITLE
Helm Controller HPA misconfiguration

### ISSUE THREAD

**Issue by anatolek** [openappsec/openappsec#250]
I'm using the latest helm version (1.1.21)

```shell
wget https://downloads.openappsec.io/packages/helm-charts/nginx-ingress/open-appsec-k8s-nginx-ingress-latest.tgz
```

HPA configuration is incorrect when `.Values.controller.kind` is `AppSecStateful`.

Please update

```yaml
...
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ingress-nginx.controller.fullname" . }}
...
```

to

```yaml
...
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ ternary "StatefulSet" "Deployment" (eq .Values.controller.kind "AppSecStateful") }}
    name: {{ include "ingress-nginx.controller.fullname" . }}
...
```
