### ISSUE TITLE
Policy is not recognized if added via Helm

### ISSUE THREAD

**Issue by anatolek** [openappsec/openappsec#251]
I'm using the latest helm version (`1.1.21`)

```shell
wget https://downloads.openappsec.io/packages/helm-charts/nginx-ingress/open-appsec-k8s-nginx-ingress-latest.tgz
```

```shell
❯ helm version
version.BuildInfo{Version:"v3.17.0", GitCommit:"301108edc7ac2a8ba79e4ebf5701b0b6ce6a31e4", GitTreeState:"clean", GoVersion:"go1.23.4"}

❯ kubectl version --client=true
Client Version: v1.32.1
Kustomize Version: v5.5.0
```

Policy configuration

```yaml
apiVersion: openappsec.io/v1beta1
kind: Policy
metadata:
  name: open-appsec-best-practice-policy-helm
spec:
  default:
    custom-response: 403-forbidden
    exceptions: []
    mode: detect-learn
    practices:
      - appsec-best-practice
    triggers:
      - appsec-log-trigger
```

---

Used AWS EKS versions: `1.30` and `1.32`
Checking the policy in the container gives this

```shell
open-appsec-open-appsec-k8s-nginx-ingress-controller-0:/# cat etc/cp/conf/waap/waap.policy
{"WAAP":{"WebAPISecurity":[],"WebApplicationSecurity":[]}}
```
But the policy exists

```shell
❯ kubectl get policies
NAME                                    AGE
open-appsec-best-practice-policy-helm   34m
```
---

Workaround:

```shell
export POLICY=$(kubectl get policy open-appsec-best-practice-policy-helm -o yaml)
kubectl delete policy open-appsec-best-practice-policy-helm
echo "$POLICY" | kubectl apply -f -
```
