### ISSUE TITLE
Nginx Proxy Manager  - Security log - error 400

### ISSUE THREAD

**Issue by antoninchadima** [openappsec/openappsec#280]
After trying to run multiple payloads with waf-bypass against open-appsec i got this error in NPM Web UI:

![Image](https://github.com/user-attachments/assets/b96b8d01-f611-4073-b5f4-c4b9645c4956)

**Comment by orianelou** [comment]
Hi, 

Can you please send the compose used, as well as any additional information that will allow us to recreate? Including how was the testing doen?

**Comment by antoninchadima** [comment]
I have used waf-bypass
after testing one site archiv.ucl.cas.cz
this error happened, before it was ok
(Maybe too much logs)

```
services:
  waf-bypass:
    image: nemesida/waf-bypass
    command: --host='archiv.ucl.cas.cz'
  appsec-agent:
    image: ghcr.io/openappsec/agent:1.1.22
    command: /cp-nano-agent
    volumes:
    - appsec-advanced-model:/advanced-model
    - appsec-conf:/etc/cp/conf
    - appsec-data:/etc/cp/data
    - appsec-localconf:/ext/appsec
    - appsec-logs:/var/log/nano_agent
    environment:
    - LEARNING_HOST=appsec-smartsync
    - SHARED_STORAGE_HOST=appsec-shared-storage
    - TUNING_HOST=appsec-tuning-svc
    - autoPolicyLoad=true
    - nginxproxymanager=true
    ipc: host
    network_mode: service:appsec-nginx-proxy-manager
    restart: unless-stopped
  appsec-db:
    image: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=xxx
    - POSTGRES_USER=appsec
    restart: unless-stopped
  appsec-nginx-proxy-manager:
    image: ghcr.io/openappsec/nginx-proxy-manager-attachment:1.1.22
    volumes:
    - appsec-localconf:/ext/appsec
    - appsec-logs:/ext/appsec-logs
    - letsencrypt:/etc/letsencrypt
    - npm:/data
    healthcheck:
      test: /bin/check-health
    environment:
    - DISABLE_IPV6=true
    ipc: host
    ports:
      - 80:80
      - 443:443
      - 81:81
    restart: unless-stopped
  appsec-shared-storage:
    image: ghcr.io/openappsec/smartsync-shared-files:1.1.22
    volumes:
    - appsec-storage:/db:z
    ipc: host
    user: root
    restart: unless-stopped
  appsec-smartsync:
    image: ghcr.io/openappsec/smartsync:1.1.22
    environment:
    - SHARED_STORAGE_HOST=appsec-shared-storage
    depends_on:
    - appsec-shared-storage
    restart: unless-stopped
  appsec-tuning-svc:
    image: ghcr.io/openappsec/smartsync-tuning:1.1.22
    volumes:
    - appsec-conf:/etc/cp/conf
    environment:
    - QUERY_DB_HOST=appsec-db
    - QUERY_DB_PASSWORD=xxx
    - QUERY_DB_USER=appsec
    - SHARED_STORAGE_HOST=appsec-shared-storage
    depends_on:
    - appsec-db
    - appsec-shared-storage
    restart: unless-stopped
volumes:
  appsec-advanced-model:
  appsec-conf:
  appsec-data:
  appsec-localconf:
  appsec-logs:
  appsec-storage:
  letsencrypt:
  npm:
  postgres:
```
