### ISSUE TITLE
Slow response when using open-appsec Ingress Controller in homelab setup

### ISSUE THREAD

**Issue by shady2k** [openappsec/openappsec#322]
**Checklist**
- Have you checked the open-appsec troubleshooting guides - https://docs.openappsec.io/troubleshooting/troubleshooting
  - Yes
- Have you checked the existing issues and discussions in github for the same issue 
  - Yes
- Have you checked the knwon limitations same issue - https://docs.openappsec.io/release-notes#limitations
  - Yes

**Describe the bug**
After installing open-appsec via Helm in a Kubernetes cluster using the official documentation, web services exposed through the open-appsec-managed NGINX ingress controller respond with significantly slow latency. Static files (CSS, JS, images) and document loads take several seconds, despite small sizes and minimal cluster resource usage.

**To Reproduce**
Follow the official guide to install open-appsec on Kubernetes:
https://docs.openappsec.io/getting-started/start-with-kubernetes/install-using-helm-new-flow-beta

Deploy a basic static site or web app behind the ingress controller

Access the service from a browser and inspect the Network tab in developer tools

Observe response delays (multi-second load times for files <100KB)

**Expected behavior**
Web requests, especially for static resources, should complete within typical response times (<1s). The current behavior introduces 3–5 second delays even for lightweight assets.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain the issue.
With open-appsec protection:
![Image](https://github.com/user-attachments/assets/dea5185f-5b3d-48dc-af1d-adc96d6167e2)

Using nginx-ingress:
![Image](https://github.com/user-attachments/assets/5887e383-b04d-449f-b44b-276df84b3bb7)

**Environment (please complete the following information):**
- open-appsec version: 1.1.26
- Deployment type: Kubernetes (Helm-based install)
- OS: Talos v1.7.6 (used across all Kubernetes worker nodes)

**Additional context**
This is a homelab deployment with three nodes
NGINX ingress pods are running without restarts
No custom policies or tuning were applied
Network latency is local (in-LAN), so the issue appears internal
Issue occurs consistently across different clients and browsers

Here is values.yaml:
```
appsec:
  mode: managed
  persistence:
    enabled: false
  userEmail: "xxx"
  agentToken: "xxx"
  configMapContent:
    crowdsec:
      enabled: true
      mode: prevent
      logging: enabled
      api:
        url: http://crowdsec-service.crowdsec.svc.cluster.local:8080/v1/decisions/stream
      auth:
        method: apikey
  secretContent:
    crowdsec:
      auth:
        data: "xxx"
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi

controller:
  ingressClass: appsec-nginx
  ingressClassResource:
    name: appsec-nginx
    controllerValue: "k8s.io/appsec-nginx"
  service:
    loadBalancerIP: "xxx"
    externalTrafficPolicy: Local
  allowSnippetAnnotations: true
  config:
    annotations-risk-level: Critical
    strict-validate-path-type: false
  enableAnnotationValidations: false
  terminationGracePeriodSeconds: 10
  kind: "DaemonSet"
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
```
