### ISSUE TITLE
OpenAppSec Nano Agent not starting inside Custom Docker image based on linux

### ISSUE THREAD

**Issue by Gregoire-Fremaux** [openappsec/openappsec#327]
**Checklist**
- Have you checked the open-appsec troubleshooting guides - https://docs.openappsec.io/troubleshooting/troubleshooting
  - Yes
- Have you checked the existing issues and discussions in github for the same issue 
  - Yes
- Have you checked the knwon limitations same issue - https://docs.openappsec.io/release-notes#limitations
  - Yes / No

**Describe the bug**
Hello, first of all, thank you for this wonderful project!

I have a small question: I tried to install openappsec in a Docker container based on a php-fpm image (I have a client using a WordPress instance with over 125 different domain names pointing to it), and I'm not able to use Nginx Proxy Manager — only a plain Nginx setup.

The installation seems to go relatively well, but when I run the command:

```lua
open-appsec-ctl --status
```
I get the following output:

```yaml
/usr/sbin/open-appsec-ctl: 1004: cannot open /etc/cp/conf/orchestration_status.json: No such file
cat: /etc/cp/conf/orchestration_status.json: No such file or directory
cat: /etc/cp/conf/agent_details.json: No such file or directory
cat: /etc/cp/conf/agent_details.json: No such file or directory
cat: /etc/cp/conf/agent_details.json: No such file or directory
Management mode: Cloud management (Visibility mode)
Agent ID: 
Profile ID: 
Policy files: 
    /etc/cp/conf/local_policy.yaml
Policy load status: Success
```
Looking further into the logs (cp-nano-http-transaction-handler-install.log), I also see:

``` bash
cp: cannot stat 'conf/cp-nano-ips-protections.json': No such file or directory
chmod: cannot access '/etc/cp/conf/data/cp-nano-ips-protections.data': No such file or directory
cp: cannot stat 'resources/cp-ab.js': No such file or directory
cp: cannot stat 'resources/cp-csrf.js': No such file or directory
chmod: cannot access '/etc/cp/conf/waap/cp-ab.js': No such file or directory
chmod: cannot access '/etc/cp/conf/waap/cp-csrf.js': No such file or directory
```

It seems like the installation didn’t create the necessary directories and files required by the nano agent, even when running the install process with sudo.

Would you happen to know why this is happening or how to fix it?

Thanks in advance!

**To Reproduce**
1. Run docker image based on : php:7.4.33-fpm
2. Install nginx after apt update && apt upgrade
3. Install OpenAppsec with: wget https://downloads.openappsec.io/open-appsec-install && chmod +x open-appsec-install 
4. open-appsec-ctl -s => show nano agent not running

**Expected behavior**
Nano agent running

**Screenshots or Logs**

**Environment (please complete the following information):**
- open-appsec version: latest
- Deployment type (Docker, Kubernetes, etc.): Inside Docker container 
- OS: Debian GNU/Linux 11 (bullseye)

**Additional context**
