### ISSUE TITLE
Why open-appsec is blocking in learn-detect mode ?

### ISSUE THREAD

**Issue by ben5556** [openappsec/openappsec#67]
I am trying out open-appsec on k8s with Kong Ingress controller. 

Name: openappsec-75c272
ID: eq6YP84yRHRTO0Ly

Deployed using the below command

```
helm install open-appsec-k8s-kong-latest.tgz \
--name-template=kong \
--set appsec.mode=standalone \
--set appsec.persistence.enabled=false \
-f values.yaml
```

And applied the below policy

```
apiVersion: openappsec.io/v1beta1
kind: Policy
metadata:
    name: open-appsec-best-practice-policy
spec:
    default:
        mode: detect-learn
        practices: [appsec-best-practice]
        triggers: [appsec-log-trigger]
        custom-response: 403-forbidden
        source-identifiers: ""
        trusted-sources: ""
        exceptions: [open-appsec-kong-exception]
```

Added the below exception:

```
apiVersion: openappsec.io/v1beta1
kind: Exception
metadata:
  name: open-appsec-kong-exception
spec:
- action: accept
  comment: "Kong config push"
  sourceIp:
  - 127.0.0.1
  url:
  - "/config"
```

BUT in the appsec container logs, I am seeing internal Kong update is blocked ? The securityAction says "Prevent" even though the mode is set to detect-learn. What am I missing ? I even added an exception to no avail.

```
"eventData": {
        "logIndex": 4550,
        "eventReferenceId": "8f1587f0-bf16-4efc-869c-dab397c5ac2a",
        "assetId": "Any",
        "assetName": "Any",
        "eventConfidence": "High",
        "sourceIP": "127.0.0.1",
        "httpSourceId": "127.0.0.1",
        "sourcePort": 48614,
        "httpHostName": "localhost:8444",
        "httpMethod": "POST",
        "httpUriPath": "/config",
        "httpUriQuery": "check_hash=1&flatten_errors=1",
        "ruleId": "Any",
        "securityAction": "Prevent",
        "waapOverride": "None",
        "practiceType": "Threat Prevention",
        "practiceSubType": "Web Application",
        "ruleName": "Any",

```

Kong ingress controller log entry:

time="2023-10-20T09:26:48Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: failed posting new config to **/config: got status code 403**" subsystem=dataplane-synchronizer
